# permissions for end users to edit githubteams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: githubteam-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: github-guard-greenhouse
    app.kubernetes.io/part-of: github-guard-greenhouse
    app.kubernetes.io/managed-by: kustomize
  name: githubteam-editor-role
rules:
- apiGroups:
  - githubguard.sap
  resources:
  - githubteams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - githubguard.sap
  resources:
  - githubteams/status
  verbs:
  - get
